// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViteLoq.Infrastructure.Persistence;

#nullable disable

namespace ViteLoq.Infrastructure.Migrations
{
    [DbContext(typeof(ViteLoqDbContext))]
    partial class ViteLoqDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ViteLoq.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ViteLoq.Domain.Entities.UserDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HeightCm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("ViteLoq.Domain.Goals.Entities.UserGymTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("UserGymTargets");
                });

            modelBuilder.Entity("ViteLoq.Domain.Goals.Entities.UserNutritionTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalTargetsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BMR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CalorieAdjustmentPerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("CurrentWeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GoalType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("ReceiveReminders")
                        .HasColumnType("bit");

                    b.Property<decimal?>("TDEE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TargetActiveMinutes")
                        .HasColumnType("int");

                    b.Property<decimal?>("TargetAlcoholGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetCalciumMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetCalories")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetCarbsGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetCholesterolMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetChromiumMcg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetCopperMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TargetExerciseSessionsPerWeek")
                        .HasColumnType("int");

                    b.Property<decimal?>("TargetFatsGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetFiberGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetFolate_Mcg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetIodineMcg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetIronMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetMagnesiumMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetManganeseMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetMoodScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetOmega3_Mg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetPhosphorusMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetPotassiumMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetProteinGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetSeleniumMcg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetSleepHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetSleepQuality")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetSodiumMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TargetSteps")
                        .HasColumnType("int");

                    b.Property<decimal?>("TargetStressLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetSugarGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetVitaminA_Ug")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetVitaminB12_Mcg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetVitaminB1_Mg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetVitaminB2_Mg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetVitaminB3_Mg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetVitaminB5_Mg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetVitaminB6_Mg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetVitaminB7_Mcg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetVitaminC_Mg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetVitaminD_IU")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetVitaminE_Mg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetVitaminK_Ug")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetWaterLiters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("TargetWeightDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TargetWeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetZincMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("UseAutoCalculatedTargets")
                        .HasColumnType("bit");

                    b.Property<int?>("WaterReminderMl")
                        .HasColumnType("int");

                    b.Property<decimal?>("WeeklyWeightChangeKg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("UserNutritionTargets");
                });

            modelBuilder.Entity("ViteLoq.Domain.Templates.Entities.NutritionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AlcoholGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Biotin_Ug")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BmrImpactKcal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BmrMultiplier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CaffeineMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CalciumMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Carbohydrate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChlorideMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CholesterolMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CopperMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("CreatineMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DHA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DefaultWeightInGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EPA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EnergyKcal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EnergyKj")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Fiber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FlavorProfile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FluorideMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Folate_Ug")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Fructose")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GlycemicIndex")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GlycemicLoad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HormonalImpactNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IngredientsText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InsulinResponseIndex")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IronMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsComposite")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLiquid")
                        .HasColumnType("bit");

                    b.Property<string>("JsonMetadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Lactose")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LocalizedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LysineMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MagnesiumMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ManganeseMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MethionineMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonounsaturatedFat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NetCarbs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Niacin_Mg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Omega3Grams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Omega6Grams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PantothenicAcid_Mg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PhosphorusMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PolyunsaturatedFat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PotassiumMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProcessingDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Protein")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Riboflavin_Mg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaltGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SatietyScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaturatedFat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SeleniumUg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SodiumMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Starch")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sugar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ThermicEffectPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Thiamin_Mg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TransFat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TryptophanMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TypicalPricePer100Grams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("VitaminA_Ug")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VitaminB12_Ug")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VitaminB6_Mg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VitaminC_Mg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VitaminD_Ug")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VitaminE_Mg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VitaminK_Ug")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WaterGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ZincMg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("NutritionItems");
                });

            modelBuilder.Entity("ViteLoq.Domain.Templates.Entities.WorkoutTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("WorkoutTemplates");
                });

            modelBuilder.Entity("ViteLoq.Domain.UserEntry.Entities.UserNutritionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Grams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("NutritionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("UserNutritionEntries");
                });

            modelBuilder.Entity("ViteLoq.Domain.UserEntry.Entities.UserWorkoutEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("UserWorkoutEntries");
                });

            modelBuilder.Entity("ViteLoq.Domain.UserTotal.Entities.UserTotalHealth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Brain")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Eyes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Heart")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Kidney")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Liver")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Lungs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pancreas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Stomach")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserTotalHealth");
                });

            modelBuilder.Entity("ViteLoq.Domain.UserTotal.Entities.UserTotalMental", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Mood")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sleep")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Stress")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserTotalMental");
                });

            modelBuilder.Entity("ViteLoq.Domain.UserTotal.Entities.UserTotalMuscle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Abs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Back")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Biceps")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Calves")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Chest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Glutes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Hamstrings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quadriceps")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Shoulders")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Triceps")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserTotalMuscle");
                });

            modelBuilder.Entity("ViteLoq.Domain.UserTotal.Entities.UserTotalSkin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("HairPoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NailsPoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SkinPoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserTotalSkin");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ViteLoq.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ViteLoq.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViteLoq.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ViteLoq.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ViteLoq.Domain.UserEntry.Entities.UserNutritionEntry", b =>
                {
                    b.HasOne("ViteLoq.Domain.Entities.AppUser", null)
                        .WithMany("UserNutritionEntry")
                        .HasForeignKey("AppUserId");
                });

            modelBuilder.Entity("ViteLoq.Domain.UserEntry.Entities.UserWorkoutEntry", b =>
                {
                    b.HasOne("ViteLoq.Domain.Entities.AppUser", null)
                        .WithMany("UserWorkoutEntry")
                        .HasForeignKey("AppUserId");
                });

            modelBuilder.Entity("ViteLoq.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("UserNutritionEntry");

                    b.Navigation("UserWorkoutEntry");
                });
#pragma warning restore 612, 618
        }
    }
}
